Use static lib since the linker had problems
/usr/lib/gcc/x86_64-alpine-linux-musl/6.4.0/../../../../lib/\
libcassandra.so: \
undefined reference to `cass::rb::RingBufferBio::initialize()'